/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { css, customElement, html, property, TemplateResult } from 'lit-element';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentItem from '../content-item/content-item';
import styles from './content-block-headlines.scss';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Content Block Headlines item
 *
 * @element dds-content-block-headlines-item
 */
@customElement(`${ddsPrefix}-content-block-headlines-item`)
class DDSContentBlockHeadlinesItem extends StableSelectorMixin(DDSContentItem) {
  /**
   * @returns The copy content.
   */
  protected _renderCopy(): TemplateResult | string | void {
    const { _hasCopy: hasCopy, _handleSlotChange: handleSlotChange } = this;
    return html`
      <p ?hidden="${!hasCopy}" class="bx--content-block-headlines__copy">
        <slot @slotchange="${handleSlotChange}"></slot>
      </p>
    `;
  }

  /**
   * @returns The heading content.
   */
  protected _renderHeading(): TemplateResult | string | void {
    const { _hasHeading: hasHeading, _handleSlotChange: handleSlotChange } = this;
    return html`
      <h4 ?hidden="${!hasHeading}" class="bx--content-block-headlines__heading">
        <slot name="heading" @slotchange="${handleSlotChange}"></slot>
      </h4>
    `;
  }

  /**
   * @returns The footer content.
   */
  protected _renderFooter(): TemplateResult | string | void {
    const { _handleSlotChange: handleSlotChange } = this;
    return html`
      <slot name="footer" @slotchange="${handleSlotChange}"></slot>
    `;
  }

  /**
   * The shadow slot this headlines item should be in.
   */
  @property({ reflect: true })
  slot = 'content';

  // `styles` here is a `CSSResult` generated by custom WebPack loader
  static get styles() {
    return css`${super.styles}${styles}`;
  }

  static get stableSelector() {
    return `${ddsPrefix}-content-block-headlines-item`;
  }
}

export default DDSContentBlockHeadlinesItem;
