/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Part } from 'lit-html';
import { classMap } from 'lit-html/directives/class-map';
import { html, property, internalProperty, LitElement, TemplateResult } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import { CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME } from './defs';
import styles from './content-block.scss';

export { CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME };

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The table mapping slot name with the private property name that indicates the existence of the slot content.
 */
const slotExistencePropertyNames = {
  complementary: '_hasComplementary',
  footer: '_hasFooter',
};

// TODO: Figure out how to define a mixin type supporting abstract class
/**
 * Content block.
 *
 * @slot heading - The heading content.
 * @slot footer - The footer (CTA) content.
 * @slot complementary - The complementary (aside) content.
 * @abstract
 */
class DDSContentBlock extends LitElement {
  /**
   * `true` if there is complementary content.
   */
  @internalProperty()
  protected _hasComplementary = false;

  /**
   * `true` if there is footer content.
   */
  @internalProperty()
  protected _hasFooter = false;

  /**
   * The CSS class list for the container (grid) node.
   */
  protected _getContainerClasses(): string | ((part: Part) => void) {
    const { complementaryStyleScheme, _hasComplementary: hasComplementary } = this;
    return classMap({
      [`${ddsPrefix}-ce--content-block__container`]: true,
      [`${ddsPrefix}-ce--content-block__container--with-complementary`]: hasComplementary,
      [`${prefix}--layout--border`]:
        hasComplementary && complementaryStyleScheme === CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME.WITH_BORDER,
    });
  }

  /**
   * Handles `slotchange` event.
   *
   * @param event The event.
   */
  protected _handleSlotChange({ target }: Event) {
    const { name } = target as HTMLSlotElement;
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .some(node => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim());
    this[slotExistencePropertyNames[name] || '_hasContent'] = hasContent;
  }

  /**
   * @returns The content, that may be wrapped in a Carbon grid.
   */
  protected _renderBody(): TemplateResult | string | void {
    return html`
      ${this._renderCopy()}${this._renderContent()}
      <div class="${ddsPrefix}-ce--content-block__footer">
        <slot name="footer" @slotchange="${this._handleSlotChange}"></slot>
      </div>
    `;
  }

  /**
   * @returns The main content.
   */
  // eslint-disable-next-line class-methods-use-this
  protected _renderContent(): TemplateResult | string | void {
    return html`
      <div class="${prefix}--content-block__children">
        <slot></slot>
      </div>
    `;
  }

  /**
   * @returns The copy content.
   */
  // eslint-disable-next-line class-methods-use-this
  protected _renderCopy(): TemplateResult | string | void {
    return html`
      <slot></slot>
    `;
  }

  /**
   * The style scheme for the complementary content.
   */
  @property({ attribute: 'complementary-style-scheme' })
  complementaryStyleScheme = CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME.REGULAR;

  render() {
    return html`
      <div class="${this._getContainerClasses()}">
        <div class="${ddsPrefix}-ce--content-block__heading">
          <slot name="heading"></slot>
        </div>
        ${this._renderBody()}
        <div class="${ddsPrefix}-ce--content-block__complementary">
          <slot name="complementary" @slotchange="${this._handleSlotChange}"></slot>
        </div>
      </div>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentBlock;
