/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { customElement, html } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import '../horizontal-rule/horizontal-rule';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentBlock from '../content-block/content-block';
import styles from './leadspace-block.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * LeadSpace Block Component.
 *
 * @element dds-leadspace-block
 */
@customElement(`${ddsPrefix}-leadspace-block`)
class DDSLeadSpaceBlock extends StableSelectorMixin(DDSContentBlock) {
  /**
   * The CSS class list for the container (grid) node.
   */
  // eslint-disable-next-line class-methods-use-this
  protected _getContainerClasses() {
    return `${ddsPrefix}-ce--leadspace-block__container`;
  }

  // eslint-disable-next-line class-methods-use-this
  protected _renderContent() {
    return html`
      <div class="${ddsPrefix}-ce--content-block__media">
        <slot name="media"></slot>
      </div>
    `;
  }

  // eslint-disable-next-line class-methods-use-this
  protected _renderCopy() {
    return html`
      <div class="${prefix}--content-block__copy">
        <slot name="copy"></slot>
      </div>
    `;
  }

  render() {
    return html`
      <div class="${this._getContainerClasses()}">
        <div class="${ddsPrefix}-ce--leadspace-block__heading">
          <slot name="block-heading"></slot>
        </div>
        <div class="${ddsPrefix}-ce--content-block__heading">
          <slot name="heading"></slot>
        </div>
        ${this._renderBody()}
        <div class="${ddsPrefix}-ce--leadspace-block__links">
          <slot name="links"></slot>
        </div>
      </div>
      <div class="${ddsPrefix}-ce--leadspace-block__hr">
        <dds-hr></dds-hr>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--leadspace-block`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSLeadSpaceBlock;
