/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { Part } from 'lit-html';
import { classMap } from 'lit-html/directives/class-map';
import { html, internalProperty, customElement, TemplateResult } from 'lit-element';
import settings from 'carbon-components/es/globals/js/settings';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings.js';
import StableSelectorMixin from '../../globals/mixins/stable-selector';
import DDSContentBlock, { CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME } from '../content-block/content-block';
import styles from './content-block-simple.scss';

const { prefix } = settings;
const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * The table mapping slot name with the private property name that indicates the existence of the slot content.
 */
const slotExistencePropertyNames = {
  complementary: '_hasComplementary',
  footer: '_hasFooter',
  media: '_hasMedia',
};

/**
 * Simple version of content block.
 *
 * @element dds-content-block-simple
 * @slot media - The media content.
 */
@customElement(`${ddsPrefix}-content-block-simple`)
class DDSContentBlockSimple extends StableSelectorMixin(DDSContentBlock) {
  /**
   * `true` if there is copy content.
   */
  @internalProperty()
  protected _hasCopy = false;

  /**
   * `true` if there is media content.
   */
  @internalProperty()
  protected _hasMedia = false;

  /**
   * The CSS class list for the container (grid) node.
   */
  protected _getContainerClasses(): string | ((part: Part) => void) {
    const { complementaryStyleScheme, _hasComplementary: hasComplementary } = this;
    return classMap({
      [`${ddsPrefix}-ce--content-block__container`]: true,
      [`${ddsPrefix}-ce--content-block__container--with-complementary`]: hasComplementary,
      [`${prefix}--layout--border`]:
        hasComplementary && complementaryStyleScheme === CONTENT_BLOCK_COMPLEMENTARY_STYLE_SCHEME.WITH_BORDER,
    });
  }

  /**
   * Handles `slotchange` event.
   *
   * @param event The event.
   */
  protected _handleSlotChange({ target }: Event) {
    const { name } = target as HTMLSlotElement;
    const hasContent = (target as HTMLSlotElement)
      .assignedNodes()
      .some(node => node.nodeType !== Node.TEXT_NODE || node!.textContent!.trim());
    this[slotExistencePropertyNames[name] || '_hasCopy'] = hasContent;
  }

  /**
   * @returns The content, that may be wrapped in a Carbon grid.
   */
  protected _renderBody(): TemplateResult | string | void {
    return html`
      ${this._renderCopy()}${this._renderContent()}
      <div class="${ddsPrefix}-ce--content-block__footer">
        <slot name="footer" @slotchange="${this._handleSlotChange}"></slot>
      </div>
    `;
  }

  // eslint-disable-next-line class-methods-use-this
  protected _renderContent() {
    const { _hasCopy: hasCopy, _hasMedia: hasMedia, _handleSlotChange: handleSlotChange } = this;
    // Renders `<div class="bx--content-item">` directly instead of using `<dds-content-item>`
    // because `<dds-content-block-simple>` uses only the copy content
    return html`
      <div ?hidden="${!hasCopy}" class="${prefix}--content-block__copy ${ddsPrefix}-ce--content-block__copy">
        <slot @slotchange="${handleSlotChange}"></slot>
      </div>
      <div ?hidden="${!hasMedia}" class="${ddsPrefix}-ce--content-block__media">
        <slot name="media" @slotchange="${handleSlotChange}"></slot>
      </div>
    `;
  }

  // eslint-disable-next-line class-methods-use-this
  protected _renderCopy() {
    return '';
  }

  render() {
    return html`
      <div class="${this._getContainerClasses()}">
        <div class="${ddsPrefix}-ce--content-block__heading">
          <slot name="heading"></slot>
        </div>
        ${this._renderBody()}
        <div class="${ddsPrefix}-ce--content-block__complementary">
          <slot name="complementary" @slotchange="${this._handleSlotChange}"></slot>
        </div>
      </div>
    `;
  }

  static get stableSelector() {
    return `${ddsPrefix}--content-block-simple`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSContentBlockSimple;
